// SPDX-FileCopyrightText: Team OpenVPI
// SPDX-License-Identifier: LGPL-3.0-or-later

#ifndef DIFFSCOPE_BATCHPROCESS_BATCHPROCESSGLOBAL_H
#define DIFFSCOPE_BATCHPROCESS_BATCHPROCESSGLOBAL_H

#include <QtCore/QtGlobal>

#if defined(BATCH_PROCESS_LIBRARY)
#    define BATCH_PROCESS_EXPORT Q_DECL_EXPORT
#else
#    define BATCH_PROCESS_EXPORT Q_DECL_IMPORT
#endif

#endif // DIFFSCOPE_BATCHPROCESS_BATCHPROCESSGLOBAL_H
