// SPDX-FileCopyrightText: Team OpenVPI
// SPDX-License-Identifier: LGPL-3.0-or-later

#ifndef DIFFSCOPE_EFFECTS_UNIT_MANAGER_EFFECTSUNITMANAGERGLOBAL_H
#define DIFFSCOPE_EFFECTS_UNIT_MANAGER_EFFECTSUNITMANAGERGLOBAL_H

#include <QtCore/QtGlobal>

#if defined(EFFECTS_UNIT_MANAGER_LIBRARY)
#    define EFFECTS_UNIT_MANAGER_EXPORT Q_DECL_EXPORT
#else
#    define EFFECTS_UNIT_MANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // DIFFSCOPE_EFFECTS_UNIT_MANAGER_EFFECTSUNITMANAGERGLOBAL_H
