#ifndef DIFFSCOPE_ACHIEVEMENT_ACHIEVEMENTGLOBAL_H
#define DIFFSCOPE_ACHIEVEMENT_ACHIEVEMENTGLOBAL_H

#include <QtCore/QtGlobal>

#if defined(ACHIEVEMENT_LIBRARY)
#  define ACHIEVEMENT_EXPORT Q_DECL_EXPORT
#else
#  define ACHIEVEMENT_EXPORT Q_DECL_IMPORT
#endif

#endif //DIFFSCOPE_ACHIEVEMENT_ACHIEVEMENTGLOBAL_H
