#ifndef DIFFSCOPE_IMPORT_EXPORT_MANAGER_COREGLOBAL_H
#define DIFFSCOPE_IMPORT_EXPORT_MANAGER_COREGLOBAL_H

#include <QtCore/QtGlobal>

#if defined(IMPORT_EXPORT_MANAGER_LIBRARY)
#    define IMPORT_EXPORT_MANAGER_EXPORT Q_DECL_EXPORT
#else
#    define IMPORT_EXPORT_MANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // DIFFSCOPE_IMPORT_EXPORT_MANAGER_COREGLOBAL_H
