#ifndef DIFFSCOPE_DSPX_MODEL_DSPXMODELGLOBAL_H
#define DIFFSCOPE_DSPX_MODEL_DSPXMODELGLOBAL_H

#include <QtCore/QtGlobal>

#if defined(DSPXMODEL_LIBRARY)
#    define DSPX_MODEL_EXPORT Q_DECL_EXPORT
#else
#    define DSPX_MODEL_EXPORT Q_DECL_IMPORT
#endif

#endif //DIFFSCOPE_DSPX_MODEL_DSPXMODELGLOBAL_H
