# SPDX-FileCopyrightText: Team OpenVPI
# SPDX-License-Identifier: Apache-2.0

name: Dev Build
on:
#  push:
#    branches:
#      - main
#    paths-ignore:
#      - 'README.md'
#      - 'LICENSE'
#      - 'crowdin.yml'
#      - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'crowdin.yml'
      - '.github/**'
      - '**/translations/*.ts'
  workflow_dispatch:
    inputs:
      identifier:
        description: 'Version identifier'
        required: false
        type: string
      use_ccache:
        description: 'Use CCache'
        required: false
        type: boolean
        default: true
      use_cache:
        description: 'Restore and save caches'
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    with:
      source_sha: ${{ github.sha }}
      build_type: dev
      version_identifier: ${{ github.sha }}${{ github.event.inputs.identifier && '.' || '' }}${{ github.event.inputs.identifier }}
      use_cache: ${{ github.event_name != 'workflow_dispatch' || inputs.use_cache }}
      use_ccache: ${{ github.event.inputs.use_ccache == 'true' }}
