#ifndef DIFFSCOPE_VISUAL_EDITOR_VISUALEDITORGLOBAL_H
#define DIFFSCOPE_VISUAL_EDITOR_VISUALEDITORGLOBAL_H

#include <QtCore/QtGlobal>

#if defined(VISUAL_EDITOR_LIBRARY)
#    define VISUAL_EDITOR_EXPORT Q_DECL_EXPORT
#else
#    define VISUAL_EDITOR_EXPORT Q_DECL_IMPORT
#endif

#endif // DIFFSCOPE_VISUAL_EDITOR_VISUALEDITORGLOBAL_H
